name: 'Install linux dependencies'
description: 'Installs all linux dependencies needed for puppeteer PDF generation'
runs:
  using: "composite"
  steps:    
    - name: Update apt-get
      shell: bash
      run: sudo apt-get update

    - name: Install linux dependencies
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: libgtk-3-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2
        version: 1.0
