name: Release
on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/move-fonts/
      - uses: ./.github/actions/install-node/
      - uses: ./.github/actions/install-and-cache-node-modules/
      - uses: ./.github/actions/install-linux-dependencies/

      - name: Build
        run: npm run build

      - name: Deploy (justin.beer)
        uses: ./.github/actions/ftp-deploy/
        with:
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: public_html/resume/

      - name: Deploy (justin-schrader.com)
        uses: ./.github/actions/ftp-deploy/
        with:
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: public_html/justin-schrader.com/resume/
