name: Release
on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@main
      - uses: ./.github/actions/install-node
      - uses: ./.github/actions/install-and-cache-node-modules
      - uses: ./.github/actions/install-linux-dependencies

      - name: Build
        run: npm run build

      - name: Release
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: cycjimmy/semantic-release-action@v4

      - name: Deploy (justin.beer)
        uses: './.github/actions/ftp-deploy'
        with:
          server-dir: public_html/resume/

      - name: Deploy (justin-schrader.com)
        uses: './.github/actions/ftp-deploy'
        with:
          server-dir: public_html/justin-schrader.com/resume/
