name: Release
on:
  push:
    branches:
      - master

permissions:
  contents: read # for checkout

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: ./.github/actions/install-node
      - uses: ./.github/actions/install-and-cache-node-modules
      - uses: ./.github/actions/install-linux-dependencies
      
      - name: Build
        run: npm run build
      - name: Archive production artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@main
      - uses: ./.github/actions/install-node
      - uses: ./.github/actions/install-and-cache-node-modules

      - name: Download artifact
        uses: actions/download-artifact@v3
        with: 
          name: dist
          path: dist

      - name: Release
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: cycjimmy/semantic-release-action@v4

      - name: Deploy justin.beer
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with: 
          server: ftp.justin.beer
          username: admin@justin.beer
          password: ${{ secrets.FTP_PASSWORD || 'mock-ftp-pass' }}
          local-dir: ./dist/
          server-dir: public_html/resume/
          dry-run: ${{ env.ACT }}

